[2021-09-10 16:21:31,435]:[cw2] [ERROR] EXCEPTION: ./slurm/DeepMindBallInCupDenseDMP-v0/log/rep_04
Traceback (most recent call last):
  File "/home/yre/anaconda3/envs/masterthesis/lib/python3.6/site-packages/cw2/job.py", line 84, in run_task
    self.exp.run(c, r, self.logger)
  File "/home/yre/anaconda3/envs/masterthesis/lib/python3.6/site-packages/cw2/experiment.py", line 79, in run
    res = self.iterate(cw_config, rep, n)
  File "cw2cmaes/cmaes_cw2.py", line 65, in iterate
    _, reward, __, ___ = self.env.step(solutions[i])
  File "/home/yre/Desktop/KIT/masterthesis/motion_primitive_env_api/mp_env_api/mp_wrappers/mp_wrapper.py", line 97, in step
    obs, rewards[t], done, info = self.env.step(actions[t, :])
  File "/home/yre/Desktop/KIT/masterthesis/Compare-Episodic-and-Step-based-Reinforcement-Learning/src/alr-envs/alr_envs/dmc/ball_in_cup/ball_in_the_cup_mp_wrapper_dense.py", line 54, in step
    action_cost = -0.001 * np.sum(np.square(action))
  File "<__array_function__ internals>", line 6, in sum
  File "/home/yre/anaconda3/envs/masterthesis/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2168, in sum
    if isinstance(a, _gentype):
KeyboardInterrupt
